services:
  rolldice:
    image: rolldice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    environment:
      - Otlp__Endpoint=http://otel-lgtm:4317
      - OTEL_METRIC_EXPORT_INTERVAL=5000  # so we don't have to wait 60s for metrics
    depends_on:
      - otel-lgtm

  otel-lgtm:
    image: grafana/otel-lgtm@sha256:475319e883b66594d1a2f22ef168c2459802bb94548e6f25d9782bd5f5c19a3a

    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318