services:
  rolldice:
    image: rolldice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    environment:
      - Otlp__Endpoint=http://otel-lgtm:4317
      - OTEL_METRIC_EXPORT_INTERVAL=5000  # so we don't have to wait 60s for metrics
    depends_on:
      - otel-lgtm

  otel-lgtm:
    image: grafana/otel-lgtm@sha256:6903a4545a4005a5cada9d44055e96d612d465f7e6d942c272ecb20e6902dec0

    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318