apiVersion: apps/v1
kind: Deployment
metadata:
 name: rolldice-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolldice-java
  template:
    metadata:
      labels:
        app: rolldice-java
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
      - name: app
        image: rolldice-java:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

