apiVersion: apps/v1
kind: Deployment
metadata:
 name: rolldice-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolldice-nodejs
  template:
    metadata:
      labels:
        app: rolldice-nodejs
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
        resource.opentelemetry.io/service.name: "dice-nodejs"
        resource.opentelemetry.io/service.namespace: "game"
        resource.opentelemetry.io/service.version: "1.2.3"
        resource.opentelemetry.io/deployment.environment.name: "production"
    spec:
      containers:
      - name: app
        image: rolldice-nodejs:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8084

